[env]
TERM = "xterm-256color"

[font]
size = 6.0

#[font.bold]
#family = "0xProto"
#style = "Bold"
#
#[font.bold_italic]
#family = "0xProto"
#style = "Bold Italic"
#
#[font.italic]
#family = "0xProto"
#style = "Italic"
#
#[font.normal]
#family = "0xProto"
#style = "Regular"

[font.offset]
x = 1
y = 1

[window.padding]
x = 6
y = 6
